### ISSUE TITLE
Net Launcher should force change when there is a network with the same name

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-net_launcher#51]
If vCloud Net Launcher finds a network with the same name, it errors:

```
E, [2014-03-10T16:17:37.162500 #8145] ERROR -- : An organization VDC network with the same name (Default) exists in the organization VDC.
```

It should instead force the change, as vCloud Edge Gateway does.

As an interim step, it could skip a network with the same name rather than erroring, but the actual solution is to force the change.

**Comment by JamesBelchamber** [comment]
Has there been any progress on this that hasn't been tracked in github? We might need to fix this for a project we have :)

**Comment by mattbostock** [comment]
Hi @JamesBelchamber, no progress since this issue was created I'm afraid. We'd very much welcome contributions.

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this pull request. Thank you for your interest and involvement in this project.
