### ISSUE TITLE
anchors support for networks.yaml in vcloud-tools

### ISSUE THREAD

**Issue by gkiselov** [gds-operations/vcloud-net_launcher#62]
Hi,
We are using vcloud-tools in our project with great success. I am trying to optimize the yaml files and make them easy for management and read. We have 5 different files to describe the environments: firewall.yaml, static-route.yaml, nat.yaml, nodes.yaml and networks.yaml
First 3 support vars.yaml file (vcloud-edge-configure --template-vars vars.yaml). It is the file, where we keep all variables. It works out of the box. I have script that converts vars.yaml file to anchors (- &dev_vse_gw_ip  '192.168.1.2' ) and this works for nodes.yaml file, but doesn't work for networks.yaml file (using vcloud-net-launch).
I'd like to see using anchors future to be available for networks as well, please. Or vcloud-net-launch and vcloud-launch to support  --template-vars vars.yaml option as well.

**Comment by surminus** [comment]
Hi Georgi,

Sorry for the delay in getting back to you. I am afraid we're no longer building new features for these tools. We can review any PRs, but please see our [Contributing Guidelines](https://github.com/gds-operations/vcloud-net_launcher/blob/master/CONTRIBUTING.md).

Thanks,
Laura
